name: Run Bash Script

on:
  push:
    branches:
      - main

jobs:
  deployment_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Execute deploy.sh script
      run: |
        chmod +x ./bash_exe.sh
        ./bash_exe.sh
